name: powersync_core
version: 1.6.0
homepage: https://powersync.com
repository: https://github.com/powersync-ja/powersync.dart
description: PowerSync Dart SDK - sync engine for building local-first apps.

environment:
  sdk: ^3.4.3

dependencies:
  sqlite_async: ^0.12.1
  # We only use sqlite3 as a transitive dependency,
  # but right now we need a minimum of v2.4.6.
  sqlite3: ^2.4.6
  # We implement a database controller, which is an interface of sqlite3_web.
  sqlite3_web: ^0.3.2
  meta: ^1.0.0
  http: ^1.5.0
  uuid: ^4.2.0
  async: ^2.10.0
  logging: ^1.1.1
  collection: ^1.19.0
  web: ^1.0.0

  # Only used internally to download WASM / worker files.
  args: ^2.6.0
  pub_semver: ^2.0.0
  pubspec_parse: ^1.3.0
  path: ^1.8.0
  typed_data: ^1.4.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.0
  test_api: ^0.7.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  stream_channel: ^2.1.2
  fake_async: ^1.3.3
  bson: ^5.0.7
  test_descriptor: ^2.0.2
  mockito: ^5.5.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
