name: powersync_web_worker
version: 0.0.1
homepage: https://powersync.com
repository: https://github.com/powersync-ja/powersync.dart
description: PowerSync Dart Web Worker Builder
environment:
  sdk: ^3.2.3

publish_to: none

executables:
  compile_worker: bin/compile_worker.dart

dev_dependencies:
  dcli: ^4.0.1
  uuid: ^4.2.0
  async: ^2.10.0
  path: ^1.8.3
  sqlite3: ^2.3.0
  drift:
    git:
      url: https://github.com/powersync-ja/drift.git
      ref: test # branch name
      path: drift

platforms:
  web:
