name: powersync_sqlcipher
version: 0.1.3
homepage: https://powersync.com
repository: https://github.com/powersync-ja/powersync.dart
description: PowerSync Flutter SDK - sync engine for building local-first apps.

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  powersync_core: ^1.1.1
  powersync_flutter_libs: ^0.4.4
  sqlcipher_flutter_libs: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test_api: ^0.7.0
  path: ^1.8.3
  path_provider: ^2.0.13

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
