name: powersync_flutter_demo
description: PowerSync Flutter Demo
publish_to: "none"

version: 1.0.1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  powersync_attachments_helper: ^0.1.4

  powersync: ^1.2.0
  path_provider: ^2.1.1
  supabase_flutter: ^2.0.1
  path: ^1.8.3
  logging: ^1.2.0
  sqlite_async: ^0.6.0
  camera: ^0.10.5+7
  image: ^4.1.3
  drift: ^2.15.0

dev_dependencies:
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
