name: powersync_flutter_demo
description: PowerSync Flutter Demo
publish_to: "none"

version: 1.0.1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  powersync: ^1.16.1
  powersync_core: ^1.6.1
  path_provider: ^2.1.1
  supabase_flutter: ^2.0.1
  path: ^1.8.3
  logging: ^1.2.0
  camera: ^0.10.5+7
  image: ^4.1.3
  universal_io: ^2.2.2
  sqlite_async: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  test: ^1.25.15

flutter:
  uses-material-design: true
  config:
    # PowerSync supports SPM, but we want to disable it in this demo so that we can keep testing
    # the CocoaPods parts of powersync_flutter_libs.
    enable-swift-package-manager: false
