name: powersync_attachments_helper
description: A helper library for handling attachments when using PowerSync.
version: 0.1.3
repository: https://github.com/powersync-ja/powersync.dart
homepage: https://www.powersync.com/
environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  powersync: ^1.0.0
  logging: ^1.2.0
  sqlite_async: ^0.6.0
  path_provider: ^2.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

platforms:
  android:
  ios:
