name: powersync_attachments_helper
description: A helper library for handling attachments when using PowerSync.
version: 0.3.0-alpha.3
repository: https://github.com/powersync-ja/powersync.dart
homepage: https://www.powersync.com/
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  powersync: 1.3.0-alpha.8
  logging: ^1.2.0
  sqlite3: "^2.4.4"
  path_provider: ^2.0.13

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
