name: powersync_attachments_helper
description: A helper library for handling attachments when using PowerSync.
version: 0.5.1
repository: https://github.com/powersync-ja/powersync.dart
homepage: https://www.powersync.com/
environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  powersync: ^1.5.0
  logging: ^1.2.0
  sqlite_async: ^0.8.1
  path_provider: ^2.0.13

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
