name: powersync
version: 1.9.3
homepage: https://powersync.com
repository: https://github.com/powersync-ja/powersync.dart
description: PowerSync Flutter SDK - sync engine for building local-first apps.
environment:
  sdk: ^3.4.0
dependencies:
  # Needed because of sqlite3_flutter_libs
  flutter:
    sdk: flutter

  sqlite3_flutter_libs: ^0.5.23
  powersync_core: ^0.0.1
  powersync_flutter_libs: ^0.4.3
  collection: ^1.17.0
  pubspec_parse: ^1.3.0
  args: ^2.5.0
  pub_semver: ^2.1.4
dev_dependencies:
  lints: ^3.0.0
  path: ^1.8.3
  path_provider: ^2.0.13

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
