name: powersync
version: 1.3.0-alpha.10
homepage: https://powersync.com
repository: https://github.com/powersync-ja/powersync.dart
description: PowerSync Flutter SDK - keep PostgreSQL databases in sync with on-device SQLite databases.
environment:
  sdk: ^3.4.0
dependencies:
  # Needed because of sqlite3_flutter_libs
  flutter:
    sdk: flutter

  sqlite_async: ^0.8.1

  universal_io: ^2.0.0
  sqlite3_flutter_libs: ^0.5.23
  powersync_flutter_libs: ^0.1.0
  meta: ^1.0.0
  http: ^1.1.0
  uuid: ^4.2.0
  async: ^2.10.0
  logging: ^1.1.1
  collection: ^1.17.0
  fetch_client: ^1.1.2
  js: ^0.7.0
dev_dependencies:
  dcli: ^4.0.0
  lints: ^3.0.0
  test: ^1.25.0
  test_api: ^0.7.0
  path_provider: ^2.0.13
  sqlite3: "^2.4.4"
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  stream_channel: ^2.1.2
  path: ^1.8.3

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
