name: powersync
version: 1.17.0
homepage: https://powersync.com
repository: https://github.com/powersync-ja/powersync.dart
description: PowerSync Flutter SDK. Sync Postgres, MongoDB or MySQL with SQLite in your Flutter app
environment:
  sdk: ^3.4.0

dependencies:
  # Needed because of sqlite3_flutter_libs
  flutter:
    sdk: flutter

  sqlite3_flutter_libs: ^0.5.39
  powersync_core: ^1.7.0
  powersync_flutter_libs: ^0.4.14
  collection: ^1.17.0

dev_dependencies:
  lints: ^5.1.0
  path: ^1.8.3
  path_provider: ^2.0.13

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
