name: supabase_todolist_drift
description: PowerSync Drift Flutter Demo
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  powersync_attachments_helper: ^0.6.5+1
  powersync: ^1.8.0
  path_provider: ^2.1.1
  supabase_flutter: ^2.0.1
  path: ^1.8.3
  logging: ^1.2.0
  camera: ^0.10.5+7
  image: ^4.1.3
  universal_io: ^2.2.2
  sqlite_async: ^0.8.1
  drift: 2.18.0
  drift_sqlite_async: ^0.1.0-alpha.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  drift_dev: 2.18.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
