name: powersync_flutter_libs
description: PowerSync core binaries for the PowerSync Flutter SDK. Needs to be included for Flutter apps.
version: 0.2.2
repository: https://github.com/powersync-ja/powersync.dart
homepage: https://www.powersync.com/

environment:
  sdk: ^3.2.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.powersync.powersync_flutter_libs
        pluginClass: PowersyncFlutterLibsPlugin
      ios:
        pluginClass: PowersyncFlutterLibsPlugin
      linux:
        pluginClass: PowersyncFlutterLibsPlugin
      macos:
        pluginClass: PowersyncFlutterLibsPlugin
      windows:
        pluginClass: PowersyncFlutterLibsPlugin
