name: supabase_anonymous_auth
description: PowerSync Supabase Anonymous Auth Demo
publish_to: "none"

version: 1.0.1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  powersync: ^1.12.1
  path_provider: ^2.1.1
  supabase_flutter: ^2.0.2
  path: ^1.8.3
  logging: ^1.2.0
  sqlite_async: ^0.11.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
